# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  database: blogfolio_db
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: blogflio_dev_db

test:
  <<: *default
  database: blogfolio_test_db
  
production:
  <<: *default
  database: blogfolio_db
